services:

  nginx:
    image: nginx:alpine
    container_name: ticketing-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ticketing-network

  database:
    image: postgres:17-alpine
    container_name: ticketing-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=ticketing_database
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

#  redis:
#    image: redis:7-alpine
#    container_name: ticketing-redis
#    restart: always
#    networks:
#      - ticketing-network

  backend:
    image: jwchoi42/ticketing-backend:latest
    container_name: ticketing-backend
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ticketing_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - ticketing-network

  frontend:
    image: jwchoi42/ticketing-frontend:latest
    container_name: ticketing-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - ticketing-network

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: ticketing-prometheus
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/prometheus/'
    depends_on:
      - backend
    networks:
      - ticketing-network

  grafana:
    image: grafana/grafana:latest
    container_name: ticketing-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/spring_boot_statistics_dashboard.json
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ticketing-network

networks:
  ticketing-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
