global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems.
  external_labels:
    monitor: 'ticketing-service-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ticketing-service'

    scrape_interval: 5s

    static_configs:
      - targets: ['application:8080']

    metrics_path: '/actuator/prometheus'

    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ticketing-service'
