# name: Continuous Deployment

# on:
#   push:
#     branches: ["main"]

# jobs:
  
#   build-and-push:
    
#     name: Build and Push to Docker Hub
#     runs-on: ubuntu-22.04
    
#     steps:

#       - name: Checkout
#         uses: actions/checkout@v5

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and Push Backend
#         uses: docker/build-push-action@v5
#         with:
#           context: ./backend
#           file: ./backend/Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticketing-backend:latest
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#       - name: Build and Push Frontend
#         uses: docker/build-push-action@v5
#         with:
#           context: ./frontend
#           file: ./frontend/Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticketing-frontend:latest
#           build-args: |
#             NEXT_PUBLIC_API_URL=/api
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#   deploy:
#     name: Deploy to EC2
#     needs: build-and-push
#     runs-on: ubuntu-22.04
    
#     steps:

#       - name: Checkout
#         uses: actions/checkout@v5

#       - name: Copy deployment files to EC2
#         uses: appleboy/scp-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           source: "compose.yaml,compose.prod.yaml,infra"
#           target: "~/"

#       - name: SSH Deploy
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
#             sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
#             sudo --preserve-env docker compose --file ~/compose.yaml --file ~/compose.prod.yaml pull
#             sudo --preserve-env docker compose --file ~/compose.yaml --file ~/compose.prod.yaml up --detach
#             sudo docker image prune --force
